### ISSUE TITLE
Unable to connect to master, out-dated image?

### ISSUE THREAD

**Issue by lerenn** [noia-network/node-docker#1]
Hi there,

I tried to use this image, but unfortunately, I can't connect to the main server.
Maybe it's on my side, but as the image has not been updated for 2 months on Docker Hub, maybe it is out-dated?

**Comment by lerenn** [comment]
Here are my logs:
```
info: [noia-node] Configuration filepath=/root/.noia-node-cli/settings.json
info: [noia-node] Setting configuration key=isHeadless oldValue=undefined newValue=true
info: [noia-node] Setting configuration key=skipBlockchain oldValue=undefined newValue=true
info: [noia-node] Setting configuration key=statisticsPath oldValue=undefined newValue=/root/.noia-node-cli/statistics.json
info: [noia-node] Setting configuration key=storage.dir oldValue=undefined newValue=/root/.noia-node-cli/storage
info: [noia-node] Setting configuration key=storage.size oldValue=undefined newValue=104857600
info: [noia-node] Setting configuration key=domain oldValue=undefined newValue=
info: [noia-node] Setting configuration key=ssl oldValue=undefined newValue=false
info: [noia-node] Setting configuration key=ssl.privateKeyPath oldValue=undefined newValue=
info: [noia-node] Setting configuration key=ssl.crtPath oldValue=undefined newValue=
info: [noia-node] Setting configuration key=ssl.crtBundlePath oldValue=undefined newValue=
info: [noia-node] Setting configuration key=publicIp oldValue=undefined newValue=
info: [noia-node] Setting configuration key=sockets.http oldValue=undefined newValue=false
info: [noia-node] Setting configuration key=sockets.http.ip oldValue=undefined newValue=0.0.0.0
info: [noia-node] Setting configuration key=sockets.http.port oldValue=undefined newValue=6767
info: [noia-node] Setting configuration key=sockets.ws oldValue=undefined newValue=false
info: [noia-node] Setting configuration key=sockets.ws.ip oldValue=undefined newValue=0.0.0.0
info: [noia-node] Setting configuration key=sockets.ws.port oldValue=undefined newValue=7676
info: [noia-node] Setting configuration key=sockets.wrtc oldValue=undefined newValue=true
info: [noia-node] Setting configuration key=sockets.wrtc.control.port oldValue=undefined newValue=8048
info: [noia-node] Setting configuration key=sockets.wrtc.control.ip oldValue=undefined newValue=0.0.0.0
info: [noia-node] Setting configuration key=sockets.wrtc.data.port oldValue=undefined newValue=8058
info: [noia-node] Setting configuration key=wallet.address oldValue=undefined newValue=0x01A51A21702eB4F510A72B27643fcD462ef0c207
info: [noia-node] Setting configuration key=wallet.mnemonic oldValue=undefined newValue=2q8a0F6DGDwWzxEHHaPx
info: [noia-node] Setting configuration key=masterAddress oldValue=undefined newValue=ws://csl-masters.noia.network:5565
info: [noia-node] Setting configuration key=whitelist.masters oldValue=undefined newValue=
info: [noia-node] Setting configuration key=controller oldValue=undefined newValue=false
info: [noia-node] Setting configuration key=controller.ip oldValue=undefined newValue=127.0.0.1
info: [noia-node] Setting configuration key=controller.port oldValue=undefined newValue=9000
info: [noia-node] Setting configuration key=nodeId oldValue=undefined newValue=6Dp79aJq8l2e3a5ghhVCxMFIEOV2yP22uHJjW0Ob
info: [noia-node] Statistics filepath=/root/.noia-node-cli/statistics.json
warn: [noia-node] connection listener added
info: [noia-node] Connecting to master ws://csl-masters.noia.network:5565
info: [noia-node] Skip blockchain, connect straight to master...
info: [noia-node] Creating wire... interface=terminal, node_ip=, node_ws_port=7676, ws=null, webrtc=8048, node_domain=, node_wallet_address=0x01A51A21702eB4F510A72B27643fcD462ef0c207
error: [noia-node] Could not connect to master message=socket hang up, stack=Error: socket hang up
    at createHangUpError (_http_client.js:331:15)
    at Socket.socketOnEnd (_http_client.js:423:23)
    at emitNone (events.js:111:20)
    at Socket.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1064:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9), code=ECONNRESET
error: [noia-contents-client] uncaughtException: socket hang up date=Sat Dec 01 2018 16:23:39 GMT+0100 (CET), pid=1, uid=0, gid=0, cwd=/usr/noia-node, execPath=/usr/local/bin/node, version=v8.11.4, argv=[/usr/local/bin/node, /usr/noia-node/dist/index.js], rss=89436160, heapTotal=70729728, heapUsed=34884208, external=17111177, loadavg=[2.1982421875, 0.82861328125, 0.3095703125], uptime=458063, trace=[column=15, file=_http_client.js, function=createHangUpError, line=331, method=null, native=false, column=23, file=_http_client.js, function=Socket.socketOnEnd, line=423, method=socketOnEnd, native=false, column=20, file=events.js, function=emitNone, line=111, method=null, native=false, column=7, file=events.js, function=Socket.emit, line=208, method=emit, native=false, column=12, file=_stream_readable.js, function=endReadableNT, line=1064, method=null, native=false, column=11, file=internal/process/next_tick.js, function=_combinedTickCallback, line=138, method=null, native=false, column=9, file=internal/process/next_tick.js, function=process._tickCallback, line=180, method=_tickCallback, native=false], stack=[Error: socket hang up,     at createHangUpError (_http_client.js:331:15),     at Socket.socketOnEnd (_http_client.js:423:23),     at emitNone (events.js:111:20),     at Socket.emit (events.js:208:7),     at endReadableNT (_stream_readable.js:1064:12),     at _combinedTickCallback (internal/process/next_tick.js:138:11),     at process._tickCallback (internal/process/next_tick.js:180:9)]
error: [noia-contents-client] uncaughtException: Cannot read property 'aborted' of null date=Sat Dec 01 2018 16:23:39 GMT+0100 (CET), pid=1, uid=0, gid=0, cwd=/usr/noia-node, execPath=/usr/local/bin/node, version=v8.11.4, argv=[/usr/local/bin/node, /usr/noia-node/dist/index.js], rss=89436160, heapTotal=70729728, heapUsed=34990224, external=17111201, loadavg=[2.1982421875, 0.82861328125, 0.3095703125], uptime=458063, trace=[column=19, file=/usr/noia-node/node_modules/ws/lib/websocket.js, function=ClientRequest.req.on, line=531, method=on, native=false, column=13, file=events.js, function=emitOne, line=116, method=null, native=false, column=7, file=events.js, function=ClientRequest.emit, line=211, method=emit, native=false, column=9, file=_http_client.js, function=Socket.socketCloseListener, line=363, method=socketCloseListener, native=false, column=13, file=events.js, function=emitOne, line=116, method=null, native=false, column=7, file=events.js, function=Socket.emit, line=211, method=emit, native=false, column=12, file=net.js, function=TCP._handle.close [as _onclose], line=557, method=close [as _onclose], native=false], stack=[TypeError: Cannot read property 'aborted' of null,     at ClientRequest.req.on (/usr/noia-node/node_modules/ws/lib/websocket.js:531:19),     at emitOne (events.js:116:13),     at ClientRequest.emit (events.js:211:7),     at Socket.socketCloseListener (_http_client.js:363:9),     at emitOne (events.js:116:13),     at Socket.emit (events.js:211:7),     at TCP._handle.close [as _onclose] (net.js:557:12)
```

**Comment by mgx259** [comment]
I have exactly the same issue on my Ubuntu 16.04 server.
Do I need to have particular version of Ubuntu or docker installed?
